In [2]:
import pandas as pd

#read in tabular data from site. 
df = pd.read_html('https://www.ncsl.org/ncsl-in-dc/standing-committees/education/cares-act-elementary-and-secondary-school-emergency-relief-fund-tracker.aspx')

df_state_total = df[0]

for col in df_state_total:
    print(col)

State  Total ESSER Allocation
Unnamed: 1
Minimum LEA Allocation
SEA Guidance to LEAs
SEA Set-Aside Amount
SEA Plan For 10% Set-Aside

In [3]:
#remove unwanted column
del df_state_total['Unnamed: 1']

In [4]:
#rename column
df_state_total.rename(columns={'State  Total ESSER Allocation':'Name'}, inplace=True)

In [5]:
#check the splits on the Name column
df_state_total.Name.str.split(expand=True)

,0,1,2,3,4,5,6,7,8,9,10,11
0,Alabama,"$216,947,540",(ESSER,I),"$899,464,932",(ESSER,II),"$2,020,070,466",(ESSER,III),None,None
1,Alaska,"$38,407,914",(ESSER,I),"$159,719,422",(ESSER,II),"$358,707,134",(ESSER,III),None,None
2,Arizona,"$277,422,944",(ESSER,I),"$1,149,715,947",(ESSER,II),"$2,582,098,697",(ESSER,III),None,None
3,Arkansas,"$128,758,638",(ESSER,I),"$558,017,409",(ESSER,II),"$1,253,227,833",(ESSER,III),None,None
4,California,"$1,647,306,127",(ESSER,I),"$6,709,633,866",(ESSER,II),"$15,068,884,546",(ESSER,III),None,None
5,Colorado,"$120,993,782",(ESSER,I),"$519,324,311",(ESSER,II),"$1,166,328,632",(ESSER,III),None,None
6,Connecticut,"$111,068,059",(ESSER,I),"$492,426,458",(ESSER,II),"$1,105,919,874",(ESSER,III),None,None
7,Delaware,"$43,492,753",(ESSER,I),"$182,885,104",(ESSER,II),"$410,733,965",(ESSER,III),None,None
8,D.C.,"$42,006,354",(ESSER,I),"$172,013,174",(ESSER,II),"$386,317,154",(ESSER,III),None,None
9,Florida,"$770,247,851",(ESSER,I),"$3,133,878,723",(ESSER,II),"$7,038,246,438",(ESSER,III),None,None
10,Georgia,"$457,169,852",(ESSER,I),"$1,892,092,618",(ESSER,II),"$4,249,371,244",(ESSER,III),None,None
11,Hawaii,"$43,385,229",(ESSER,I),"$183,595,211",(ESSER,II),"$412,328,764",(ESSER,III),None,None
12,Idaho,"$47,854,695",(ESSER,I),"$195,890,413",(ESSER,II),"$439,942,041",(ESSER,III),None,None
13,Ilinois,"$569,467,218",(ESSER,I),"$2,250,804,891",(ESSER,II),"$5,054,988,054",(ESSER,III),None,None
14,Indiana,"$214,472,770",(ESSER,I),"$888,183,537",(ESSER,II),"$1,994,734,056",(ESSER,III),None,None
15,Iowa,"$71,625,561",(ESSER,I),"$344,864,294",(ESSER,II),"$774,516,216",(ESSER,III),None,None
16,Kansas,"$84,529,061",(ESSER,I),"$344,864,294",(ESSER,II),"$830,585,182",(ESSER,III),None,None
17,Kentucky,"$193,186,874",(ESSER,I),"$928,274,720",(ESSER,II),"$2,084,773,157",(ESSER,III),None,None
18,Louisiana,"$286,980,175",(ESSER,I),"$1,160,119,378",(ESSER,II),"$2,605,463,325",(ESSER,III),None,None
19,Maine,"$43,793,319",(ESSER,I),"$183,138,601",(ESSER,II),"$411,303,282",(ESSER,III),None,None
20,Maryland,"$207,834,058",(ESSER,I),"$868,771,243",(ESSER,II),"$1,951,136,802",(ESSER,III),None,None
21,Massachusetts,"$214,894,317",(ESSER,I),"$814,890,396",(ESSER,II),"$1,830,128,073",(ESSER,III),None,None
22,Michigan,"$389,796,984",(ESSER,I),"$1,656,308,286",(ESSER,II),"$3,719,833,128",(ESSER,III),None,None
23,Minnesota,"$140,137,253",(ESSER,I),"$588,036,257",(ESSER,II),"$1,320,645,901",(ESSER,III),None,None
24,Mississippi,"$169,883,002",(ESSER,I),"$724,532,847",(ESSER,II),"$1,627,197,854",(ESSER,III),None,None
25,Missouri,"$208,443,300",(ESSER,I),"$871,172,291",(ESSER,II),"$1,956,529,215",(ESSER,III),None,None
26,Montana,"$41,295,230",(ESSER,I),"$170,099,465",(ESSER,II),"$382,019,236",(ESSER,III),None,None
27,Nebraska,"$65,085,085",(ESSER,I),"$243,073,530",(ESSER,II),"$545,908,619",(ESSER,III),None,None
28,Nevada,"$117,185,045",(ESSER,I),"$477,322,438",(ESSER,II),"$1,071,998,392",(ESSER,III),None,None
29,New,Hampshire,"$37,641,372",(ESSER,I),"$156,065,807",(ESSER,II),"$350,501,633",(ESSER,III),t
30,New,Jersey,"$310,371,213",(ESSER,I),"$1,230,971,757",(ESSER,II),"$2,764,587,703",(ESSER,III),None
31,New,Mexico,"$108,574,786",(ESSER,I),"$435,938,638",(ESSER,II),"$979,056,256",(ESSER,III),None
32,New,York,"$1,037,045,603",(ESSER,I),"$4,002,381,738",(ESSER,II),"$8,988,780,836",(ESSER,III),None
33,North,Carolina,"$396,311,607",(ESSER,I),"$1,602,590,987",(ESSER,II),"$3,599,191,706",(ESSER,III),None
34,North,Dakota,"$33,297,699",(ESSER,I),"$135,924,393",(ESSER,II),"$305,266,879",(ESSER,III),None
35,Ohio,"$489,205,200",(ESSER,I),"$1,991,251,095",(ESSER,II),"$4,472,067,097",(ESSER,III),None,None
36,Oklahoma,"$160,950,476",(ESSER,I),"$665,038,753",(ESSER,II),"$1,493,582,570",(ESSER,III),None,None
37,Oregon,"$121,099,019",(ESSER,I),"$499,153,891",(ESSER,II),"$1,121,028,734",(ESSER,III),None,None
38,Pennsylvania,"$523,807,198",(ESSER,I),"$2,224,964,030",(ESSER,II),"$4,996,953,151",(ESSER,III),None,None
39,Rhode,Island,"$46,350,444",(ESSER,I),"$184,791,567",(ESSER,II),"$415,015,610",(ESSER,III),None
40,South,Carolina,"$216,311,158",(ESSER,I),"$940,420,782",(ESSER,II),"$2,112,051,487",(ESSER,III),None
41,South,Dakota,"$41,295,230",(ESSER,I),"$170,099,465",(ESSER,II),"$382,019,236",(ESSER,III),None
42,Tennessee,"$259,891,154",(ESSER,I),"$1,107,656,022",(ESSER,II),"$2,487,638,081",(ESSER,III),None,None
43,Texas,"$1,285,886,064",(ESSER,I),"$5,529,552,209",(ESSER,II),"$12,418,588,778",(ESSER,III),None,None
44,Utah,"$67,821,787",(ESSER,I),"$274,071,684",(ESSER,II),"$615,526,070",(ESSER,III),None,None
45,Vermont,"$31,148,360",(ESSER,I),"$126,973,363",(ESSER,II),"$285,164,138",(ESSER,III),None,None
46,Virginia,"$238,599,192",(ESSER,I),"$939,280,578",(ESSER,II),"$2,109,490,751",(ESSER,III),None,None
47,Washington,"$216,892,447",(ESSER,I),"$824,852,290",(ESSER,II),"$1,852,501,071",(ESSER,III),None,None
48,West,Virginia,"$86,640,471",(ESSER,I),"$339,032,096",(ESSER,II),"$761,417,928",(ESSER,III),None
49,Wisconsin,"$174,777,774",(ESSER,I),"$686,056,238",(ESSER,II),"$1,540,784,854",(ESSER,III),None,None
50,Wyoming,"$32,562,651",(ESSER,I),"$135,230,900",(ESSER,II),"$303,709,391",(ESSER,III),None,None

In [6]:
#split the Name column for ESSER Fundings
df_state_total[['0','1','2','3','4','5','6','7','8','9','10','11']] = df_state_total.Name.str.split(expand=True)

In [7]:
#clean data for ESSER State & ESSER I
df_state_total["State"] = df_state_total["0"] + df_state_total["1"] + df_state_total["2"]

df_state_total[["State", "ESSER I"]] = df_state_total.State.str.split("$",expand=True)

df_state_total['ESSER I'] = df_state_total['ESSER I'].apply(lambda x: x.split('(')[0])

#add $ to front 

df_state_total['ESSER I'] = '$' + df_state_total['ESSER I'].astype(str)

del df_state_total['Name']
del df_state_total['0']
del df_state_total['1']
del df_state_total['2']
del df_state_total['3']

In [8]:
#create ESSER II
df_state_total["ESSER II"] = df_state_total["4"] + df_state_total["5"]

#clean ESSER II
df_state_total['ESSER II'] = df_state_total['ESSER II'].apply(lambda x: x.split('(')[0])
df_state_total['ESSER II'] = df_state_total['ESSER II'].map(lambda x: x.lstrip('I)'))

del df_state_total['4']
del df_state_total['5']

In [9]:
#create ESSER III
df_state_total["ESSER III"] = df_state_total["7"] + df_state_total["8"]

#clean ESSER II
df_state_total['ESSER III'] = df_state_total['ESSER III'].apply(lambda x: x.split('(')[0])
df_state_total['ESSER III'] = df_state_total['ESSER III'].map(lambda x: x.lstrip('II)'))

del df_state_total['6']
del df_state_total['7']
del df_state_total['8']
del df_state_total['9']
del df_state_total['10']
del df_state_total['11']

In [22]:
df_state_total_view = df_state_total[['State', 'ESSER I', 'ESSER II', 'ESSER III', 'SEA Plan For 10% Set-Aside']]

In [23]:
df_state_total_view

,State,ESSER I,ESSER II,ESSER III,SEA Plan For 10% Set-Aside
0,Alabama,"$216,947,540","$899,464,932","$2,020,070,466",ESSER I: “The Alabama State Department of Educ...
1,Alaska,"$38,407,914","$159,719,422","$358,707,134",The Alaska Department of Education & Early Dev...
2,Arizona,"$277,422,944","$1,149,715,947","$2,582,098,697","ESSER I: ""The Arizona Department of Education ..."
3,Arkansas,"$128,758,638","$558,017,409","$1,253,227,833","ESSER I: ""The Arkansas Division of Elementary ..."
4,California,"$1,647,306,127","$6,709,633,866","$15,068,884,546",The California Department of Education has dir...
5,Colorado,"$120,993,782","$519,324,311","$1,166,328,632",ESSER I: The Colorado Department of Education ...
6,Connecticut,"$111,068,059","$492,426,458","$1,105,919,874",ESSER I: The Connecticut State Department of E...
7,Delaware,"$43,492,753","$182,885,104","$410,733,965","ESSER I: ""The Delaware Department of Education..."
8,D.C.,"$42,006,354","$172,013,174","$386,317,154","ESSER I: ""OSSE plans to use their set-aside fu..."
9,Florida,"$770,247,851","$3,133,878,723","$7,038,246,438",ESSER I: “The Florida Department of Education ...
10,Georgia,"$457,169,852","$1,892,092,618","$4,249,371,244",ESSER I:The Georgia Department of Education is...
11,Hawaii,"$43,385,229","$183,595,211","$412,328,764",The Hawaii Department of Education will use it...
12,Idaho,"$47,854,695","$195,890,413","$439,942,041",ESSER I: The Idaho State Board of Education wi...
13,Ilinois,"$569,467,218","$2,250,804,891","$5,054,988,054",ESSER I: Illinois State Board of Education (IS...
14,Indiana,"$214,472,770","$888,183,537","$1,994,734,056",ESSER I: The Indiana Department of Education i...
15,Iowa,"$71,625,561","$344,864,294","$774,516,216",Governor Reynolds and the Iowa Department of E...
16,Kansas,"$84,529,061","$344,864,294","$830,585,182",ESSER I: “Kansas does not intend to use any of...
17,Kentucky,"$193,186,874","$928,274,720","$2,084,773,157",ESSER I: “The Kentucky Department of Education...
18,Louisiana,"$286,980,175","$1,160,119,378","$2,605,463,325",The Lousiana Department of Education intends t...
19,Maine,"$43,793,319","$183,138,601","$411,303,282","ESSER I: ""The Maine Department of Education in..."
20,Maryland,"$207,834,058","$868,771,243","$1,951,136,802","""The Maryland State Department of Education wi..."
21,Massachusetts,"$214,894,317","$814,890,396","$1,830,128,073",ESSER I: “The Massachusetts Department of Educ...
22,Michigan,"$389,796,984","$1,656,308,286","$3,719,833,128",ESSER I: “The Michigan Department of Education...
23,Minnesota,"$140,137,253","$588,036,257","$1,320,645,901",ESSER I: “The Minnesota Department of Educatio...
24,Mississippi,"$169,883,002","$724,532,847","$1,627,197,854",“The Mississippi Department of Education inten...
25,Missouri,"$208,443,300","$871,172,291","$1,956,529,215",“The Missouri Department of Elementary and Sec...
26,Montana,"$41,295,230","$170,099,465","$382,019,236",ESSER I: The Montana Office of Public Instruct...
27,Nebraska,"$65,085,085","$243,073,530","$545,908,619",“The Nebraska Department of Education intends ...
28,Nevada,"$117,185,045","$477,322,438","$1,071,998,392",“The Nevada Department of Education intends to...
29,NewHampshire,"$37,641,372","$156,065,807","$350,501,633",“The New Hampshire Department of Education int...
30,NewJersey,"$310,371,213","$1,230,971,757","$2,764,587,703","ESSER I: ""The New Jersey Department of Educati..."
31,NewMexico,"$108,574,786","$435,938,638","$979,056,256",“ESSER I: The New Mexico Public Education Depa...
32,NewYork,"$1,037,045,603","$4,002,381,738","$8,988,780,836",ESSER I: ESSER funds to school districts were ...
33,NorthCarolina,"$396,311,607","$1,602,590,987","$3,599,191,706",ESSER I: “The North Carolina State Board of Ed...
34,NorthDakota,"$33,297,699","$135,924,393","$305,266,879",“The North Dakota Department of Public Instruc...
35,Ohio,"$489,205,200","$1,991,251,095","$4,472,067,097",ESSER I: The Ohio Department of Education is u...
36,Oklahoma,"$160,950,476","$665,038,753","$1,493,582,570",ESSER I: Governor Kevin Stitt and State Supt. ...
37,Oregon,"$121,099,019","$499,153,891","$1,121,028,734",ESSER I: The Oregon Department of Education (O...
38,Pennsylvania,"$523,807,198","$2,224,964,030","$4,996,953,151",“The Pennsylvania Department of Education inte...
39,RhodeIsland,"$46,350,444","$184,791,567","$415,015,610","""The Rhode Island Department of Education inte..."
40,SouthCarolina,"$216,311,158","$940,420,782","$2,112,051,487",“The South Carolina Department of Education (S...
41,SouthDakota,"$41,295,230","$170,099,465","$382,019,236",“The South Dakota Department of Education (SDD...
42,Tennessee,"$259,891,154","$1,107,656,022","$2,487,638,081",ESSER I: The Tennessee Department of Education...
43,Texas,"$1,285,886,064","$5,529,552,209","$12,418,588,778",“The Texas Education Agency (TEA) will reserve...
44,Utah,"$67,821,787","$274,071,684","$615,526,070",ESSER I: “The Utah State Board of Education in...
45,Vermont,"$31,148,360","$126,973,363","$285,164,138",ESSER I: “The Vermont Agency of Education inte...
46,Virginia,"$238,599,192","$939,280,578","$2,109,490,751",ESSER I: The Virginia Department of Education ...
47,Washington,"$216,892,447","$824,852,290","$1,852,501,071",Of the 10% of the total ESSER funds is allocat...
48,WestVirginia,"$86,640,471","$339,032,096","$761,417,928",ESSER I:The West Virginia Department of Educat...
49,Wisconsin,"$174,777,774","$686,056,238","$1,540,784,854",ESSER I: The Wisconsin Department of Public In...
50,Wyoming,"$32,562,651","$135,230,900","$303,709,391","""The Wyoming Department of Education will use ..."

In [26]:
df_state_total_view.to_csv(r'ESSER_State_Totals.csv')